### ISSUE TITLE
Change main branch from master to main

### ISSUE THREAD

**Issue by aradmargalit** [eshedmargalit/paperaweek#132]
I recently pushed `main`, which is branched from the head of master. Could somebody with admin permissions please:
1. Change `main` to be the default branch
2. Delete the `master` branch?

This is in line with GitHub's default behavior for new repos. Thanks!

**Comment by eshedmargalit** [comment]
I'm going to use GitHub's setting to rename `master` -> `main`, but I need to delete the current main first. Thanks for getting the ball rolling here!

**Comment by eshedmargalit** [comment]
Done.
